# Generated by Django 5.1.7 on 2025-07-08 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0011_cashsession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='fixed_quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Получено изначально'),
        ),
    ]
