# Generated by Django 5.1.7 on 2025-07-08 11:42

import clients.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0013_alter_stock_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='date_added',
            field=models.DateField(default=clients.models.current_date),
        ),
    ]
