# Generated by Django 5.1.7 on 2025-07-08 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0014_alter_stock_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='code',
            field=models.CharField(max_length=255),
        ),
    ]
